name: CI build (.NET Framework)

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: windows-latest

    env:
      Solution_Name: Purrfect-Blog.sln
      Build_Configuration: Release

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore packages
        run: nuget restore "$env:Solution_Name"

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build
        run: msbuild "$env:Solution_Name" /t:Rebuild /p:Configuration=$env:Build_Configuration /p:Platform="Any CPU" /m
